name: Node.js CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14' ]
    steps:
      - uses: actions/checkout@v2
      - name: Configuring node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm install
      - name: Testing
        run: npm test
